#!/bin/bash
echo "Como te llamas?"
read name
echo "Hola $name, como estas?"
read -p "$name,  ingresa un numero para sumar:" a
read -p "$name,  ingresa otro numero para sumar:" b
echo "$name, la suma es:$((a+b))"
